name: "Pull Request main"
on:
    pull_request:
        branches:
            - main

jobs:
    lintAndTest:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: "Install Node"
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "yarn"
            - name: Install dependencies
              run: yarn install
            - name: "Run lint"
              run: yarn run lint
            - name: "Run Test"
              run: yarn test
